name: Books
sites:
  - name: D&R
    address: https://www.dr.com.tr
    search: /search?q=%s
    link: a.prd-name
    value: .prd:first-child div.prd-price

  - name: Kitapyurdu
    address: https://www.kitapyurdu.com
    search: /index.php?route=product/search&filter_name=%s
    link: div#product-table .product-cr:first-child .name a[href]
    value: div#product-table .product-cr:first-child .price-new  span.value

  - name: Hepsiburada
    address: https://www.hepsiburada.com
    search: /ara?q=%s
    link: .productListContent-item:first-child div[data-test-id=product-card-container] a[href]
    value: .productListContent-item:first-child div[data-test-id=price-current-price]

  - name: Trendyol
    address: https://www.trendyol.com
    search: /sr?q=%s
    link: .prdct-cntnr-wrppr .p-card-wrppr:first-child a[href]
    value: .prdct-cntnr-wrppr .p-card-wrppr:first-child .prc-box-sllng

  - name: Amazon
    address: https://www.amazon.com.tr
    search: /s?k=%s
    link: .s-search-results .sg-col-inner a.a-link-normal[href]
    value: .s-search-results .sg-col-inner span.a-offscreen
