name: Books
sites:
  - name: D&R
    address: https://www.dr.com.tr
    steps:
      - id: 0
        selector: /search?q=%s
        action: SEARCH
      - id: 1
        selector: .list-cell:first-child .item-name
        action: LINK
      - id: 2
        selector: .list-cell:first-child .price
        action: VALUE