name: Books
sites:
  - name: D&R
    address: https://www.dr.com.tr
    search: /search?q=%s
    link: .list-cell:first-child .item-name
    value: .list-cell:first-child .price

  - name: Kitapyurdu
    address: https://www.kitapyurdu.com
    search: /index.php?route=product/search&filter_name=%s
    link: div#product-table .product-cr:first-child .name a[href]
    value: div#product-table .product-cr:first-child .price-new  span.value

  - name: Hepsiburada
    address: https://www.hepsiburada.com
    search: /ara?q=%s
    link: ul.product-list li.search-item:nth-child(2) a[href]
    value: ul.product-list li.search-item:nth-child(2) .product-price

  - name: Trendyol
    address: https://www.trendyol.com
    search: /sr?q=%s
    link: .prdct-cntnr-wrppr .p-card-wrppr:first-child a[href]
    value: .prdct-cntnr-wrppr .p-card-wrppr:first-child .prc-box-sllng

  - name: Amazon
    address: https://www.amazon.com.tr
    search: /s?k=%s
    link: .s-search-results .s-result-item:first-child a.a-link-normal[href]
    value: .s-search-results .s-result-item:first-child .a-price:first-child .a-offscreen
