name: Books
sites:
  - name: D&R
    address: https://www.dr.com.tr
    steps:
      - id: 0
        selector: /search?q=%s
        action: SEARCH
      - id: 1
        selector: .list-cell:first-child .item-name
        action: LINK
      - id: 2
        selector: .list-cell:first-child .price
        action: VALUE
  - name: Kitapyurdu
    address: https://www.kitapyurdu.com
    steps:
      - id: 0
        selector: /index.php?route=product/search&filter_name=%s
        action: SEARCH
      - id: 1
        selector: ul.product-grid li:first-child .pr-img-link
        action: LINK
      - id: 2
        selector: ul.product-grid li:first-child .price .value
        action: VALUE
  - name: Hepsiburada
    address: https://www.hepsiburada.com
    steps:
      - id: 0
        selector: /ara?q=%s
        action: SEARCH
      - id: 1
        selector: ul.product-list li.search-item:nth-child(2) a[href]
        action: LINK
      - id: 2
        selector: ul.product-list li.search-item:nth-child(2) .product-price
        action: VALUE
  - name: Trendyol
    address: https://www.trendyol.com
    steps:
      - id: 0
        selector: /sr?q=%s
        action: SEARCH
      - id: 1
        selector: .prdct-cntnr-wrppr .p-card-wrppr:first-child a[href]
        action: LINK
      - id: 2
        selector: .prdct-cntnr-wrppr .p-card-wrppr:first-child .prc-box-sllng
        action: VALUE